version: "3.7"

services:
  lms:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - APP_PORT=3001
      - DB_HOST=mongonode
    command: npm run dev
    networks:
      - server_node

networks:
  server_node:
    external: true
